name: CMake

on:
  push:
    branches: '**'
  pull_request:
    branches: '**'

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    
    - name: Install Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.3.2'
        archives: qtbase ${{ startsWith(matrix.os, "ubuntu-") && "icu" || ""}}
        cache: 'true'
        cache-key-prefix: 'install-qt-action'

    - name: Configure CMake
      run: cmake -S ${{github.workspace}}/src -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      
    - name: View build folder
      shell: pwsh
      run: Get-ChildItem -Path ${{github.workspace}}/src -Recurse -ErrorAction SilentlyContinue -Force | Resolve-Path -Relative| %{$_.replace('\', '/')}
